name: deep_learning_for_vision_systems
channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py39h2bbff1b_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - bottleneck=1.3.2=py39h7cc1a96_1
  - ca-certificates=2021.5.30=h5b45459_0
  - certifi=2021.5.30=py39hcbf5309_0
  - cffi=1.14.6=py39h2bbff1b_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cycler=0.10.0=py39haa95532_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py39haa95532_0
  - freeglut=3.2.1=h0e60522_2
  - freetype=2.10.4=hd328e21_0
  - icu=68.1=h0e60522_0
  - importlib-metadata=3.10.0=py39haa95532_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - intel-openmp=2021.2.0=haa95532_616
  - ipykernel=5.3.4=py39h7b7c402_0
  - ipython=7.22.0=py39hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - jasper=2.0.14=h77af90b_2
  - jedi=0.17.2=py39haa95532_1
  - jinja2=3.0.1=pyhd3eb1b0_0
  - jpeg=9d=h8ffe710_0
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py39haa95532_7
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py39haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.3.1=py39hd77b12b_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libclang=11.1.0=default_h5c34c98_1
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - liblapacke=3.9.0=5_hd5c7e75_netlib
  - libopencv=4.5.2=py39h3a52993_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.15.8=h7755175_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.2.0=hd0e1b90_0
  - libwebp-base=1.2.0=h8ffe710_2
  - lz4-c=1.9.3=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.0.1=py39h2bbff1b_0
  - matplotlib=3.3.4=py39haa95532_0
  - matplotlib-base=3.3.4=py39h49ac443_0
  - mistune=0.8.4=py39h2bbff1b_1000
  - mkl=2021.2.0=haa95532_296
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.0=py39h277e83a_2
  - mkl_random=1.2.2=py39hf11a4ad_0
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py39haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.0=py39haa95532_0
  - numexpr=2.7.3=py39hb80d3ca_1
  - olefile=0.46=py_0
  - opencv=4.5.2=py39hcbf5309_0
  - openssl=1.1.1k=h8ffe710_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandas=1.2.5=py39hd77b12b_0
  - pandocfilters=1.4.3=py39haa95532_1
  - parso=0.7.0=py_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.3.1=py39h4fa10fc_0
  - pip=21.1.3=py39haa95532_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - prompt_toolkit=3.0.17=hd3eb1b0_0
  - py-opencv=4.5.2=py39h832f523_0
  - pycparser=2.20=py_2
  - pygments=2.9.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.12.3=py39hcbf5309_7
  - pyqt-impl=5.12.3=py39h415ef7b_7
  - pyqt5-sip=4.19.18=py39h415ef7b_7
  - pyqtchart=5.12=py39h415ef7b_7
  - pyqtwebengine=5.12.1=py39h415ef7b_7
  - pyrsistent=0.18.0=py39h2bbff1b_0
  - python=3.9.5=h6244533_3
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2021.1=pyhd3eb1b0_0
  - pywin32=228=py39he774522_0
  - pywinpty=0.5.7=py39haa95532_0
  - pyzmq=20.0.0=py39hd77b12b_1
  - qt=5.12.9=h5909a2a_4
  - qtconsole=5.1.0=pyhd3eb1b0_0
  - qtpy=1.9.0=py_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py39haa95532_0
  - sip=4.19.13=py39hd77b12b_0
  - sqlite=3.36.0=h2bbff1b_0
  - terminado=0.9.4=py39haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.10=he774522_0
  - tornado=6.1=py39h2bbff1b_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - tzdata=2021a=h52ac0ba_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py39haa95532_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py39haa95532_0
  - wincertstore=0.2=py39h2bbff1b_0
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_0
  - zeromq=4.3.3=ha925a31_3
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - absl-py==0.13.0
    - astunparse==1.6.3
    - cachetools==4.2.2
    - charset-normalizer==2.0.2
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==1.33.0
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.34.1
    - h5py==3.1.0
    - idna==3.2
    - keras==2.4.3
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - protobuf==3.17.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyyaml==5.4.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scipy==1.7.0
    - six==1.15.0
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.5.0
    - tensorflow-estimator==2.5.0
    - termcolor==1.1.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.6
    - werkzeug==2.0.1
    - wrapt==1.12.1
prefix: C:\Users\Chris Centrella\.conda\envs\deep_learning_for_vision_systems
